apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - args:
        - python3
        - -u
        - manage.py
        - runserver
        - 0.0.0.0:8000
        image: gcr.io/bus-delay-208318/backend:v2
        name: backend
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
